services:
  api:
    container_name: ablapi
    hostname: ablapi
    build:
      context: ./Solution
#    image: ghcr.io/ableytner/ablapi:dev
    ports:
      - 9219:8000
    environment:
      ElkConfig__ApiKey: "${ELK_API_KEY}"
      Database__Connection: "${DB_CONNECTION_STRING}"
      JwtConfig__Key: "${JWT_KEY}"
      GithubConfig__Token: "${GITHUB_TOKEN}"
    restart: unless-stopped
