using AblApi.Common.Enums;
using DbUp;
using DbUp.Engine;
using Microsoft.Data.Sqlite;

namespace AblApi.DataAccess;

public class DbMigrationHandler
{
    private readonly DatabaseType _type;
    private readonly string _connectionString;
    private readonly UpgradeEngine _upgradeEngine;

    public DbMigrationHandler(DatabaseType type, string connectionString)
    {
        _type = type;
        _connectionString = connectionString;

        _upgradeEngine = type switch
        {
            DatabaseType.Postgres => DeployChanges.To
                .PostgresqlDatabase(connectionString)
                .WithScriptsEmbeddedInAssembly(typeof(DbMigrationHandler).Assembly)
                .LogToConsole()
                .WithTransactionPerScript()
                .Build(),
            DatabaseType.Sqlite => DeployChanges.To
                .SqliteDatabase(connectionString)
                .WithScriptsEmbeddedInAssembly(typeof(DbMigrationHandler).Assembly)
                .WithPreprocessor(new SqlitePrimaryKeyPreprocessor())
                .LogToConsole()
                .WithTransactionPerScript()
                .Build(),
            _ => throw new InvalidOperationException("Unknown database type")
        };
    }

    public void Migrate()
    {
        // create database if it does not exist
        switch (_type)
        {
            case DatabaseType.Postgres:
                EnsureDatabase.For.PostgresqlDatabase(_connectionString);
                break;
            case DatabaseType.Sqlite:
                using (var connection = new SqliteConnection(_connectionString))
                {
                    connection.Open();
                }
                break;
            default:
                throw new InvalidOperationException("Unknown database type");
        }

        int retries = 3;
        while (retries > 0)
        {
            try
            {
                if (_upgradeEngine.IsUpgradeRequired())
                {
                    DatabaseUpgradeResult result = _upgradeEngine.PerformUpgrade();
                }
                return;
            }
            catch (Exception)
            {
                Thread.Sleep(1000);
                retries--;

                if (retries == 0)
                {
                    throw;
                }
            }
        }
    }

    public bool NeedsMigration()
    {
        return _upgradeEngine.IsUpgradeRequired();
    }
}

// Sqlite does not support PostgreSQL's "GENERATED BY DEFAULT AS IDENTITY" syntax for auto-generated primary keys.
// Sqlite requires AUTOINCREMENT to be declared inline as "INTEGER PRIMARY KEY AUTOINCREMENT" on the column itself,
// so the separate table-level PRIMARY KEY constraint for that column has to be removed as well.
// This is done per CREATE TABLE block, so that identically named columns in other tables (e.g. "Id") are not affected.
public class SqlitePrimaryKeyPreprocessor : IScriptPreprocessor
{
    public string Process(string contents)
    {
        string[] blocks = contents.Replace("\r\n", "\n").Split("\n\n");

        for (int c = 0; c < blocks.Length; c++)
        {
            if (blocks[c].TrimStart().StartsWith("CREATE TABLE"))
            {
                blocks[c] = ProcessCreateTableBlock(blocks[c]);
            }
        }

        return string.Join("\n\n", blocks);
    }

    private static string ProcessCreateTableBlock(string block)
    {
        string[] lines = block.Trim().Split("\n");
        var changedColumnNames = new List<string>();

        for (int c = 0; c <  lines.Length; c++)
        {
            // replace lines which define identity columns with the SQLite equivalent
            if (lines[c].Contains("GENERATED BY DEFAULT AS IDENTITY"))
            {
                int firstQuote = lines[c].IndexOf('"');
                int secondQuote = lines[c].IndexOf('"', firstQuote + 1);
                string columnName = lines[c].Substring(firstQuote + 1, secondQuote - firstQuote - 1);
                changedColumnNames.Add(columnName);

                string indent = lines[c].Substring(0, lines[c].IndexOf('"'));
                lines[c] = $"{indent}\"{columnName}\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,";
            }

            // remove lines which create PK constraints for the changed columns
            if (lines[c].Contains("CONSTRAINT") && lines[c].Contains("PRIMARY KEY") && changedColumnNames.Any(name => lines[c].Contains($"\"{name}\"")))
            {
                if (c > 0 && c == lines.Length - 2 && lines[c - 1].TrimEnd().EndsWith(','))
                {
                    lines[c - 1] = lines[c - 1].TrimEnd().TrimEnd(',');
                }
                lines[c] = "";
            }
        }

        return string.Join("\n", lines.Where(line => !string.IsNullOrWhiteSpace(line)));
    }
}
