<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AblApi.DataAccess\AblApi.DataAccess.csproj" />
    <ProjectReference Include="..\AblApi.Repositories\AblApi.Repositories.csproj" />
    <ProjectReference Include="..\AblApi.Common\AblApi.Common.csproj" />
    <ProjectReference Include="..\AblApi.Core\AblApi.Core.csproj" />
  </ItemGroup>

</Project>
