-- Initial database schema for AblApi

CREATE TABLE "ApiUsers"
(
	"Id" uuid NOT NULL,
	"Name" varchar(64) NOT NULL,
	"Token" varchar(64) NOT NULL,
	CONSTRAINT "PK_ApiUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "ApiAccessRoleGrants"
(
	"Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserId" uuid NOT NULL,
	"Role" integer NOT NULL,
	"GrantedAt" timestamp NOT NULL,
	CONSTRAINT "PK_ApiAccessRoleGrants" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_ApiAccessRoleGrants_ApiUsers" FOREIGN KEY ("UserId")
		REFERENCES "ApiUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GTNHStableVersions"
(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Version" varchar(32) NOT NULL,
	"CreatedAt" timestamp NOT NULL,
	"ClientDownloadUrl" varchar(255) NOT NULL,
	"ClientDownloadUrlJava8" varchar(255) NOT NULL,
	"ServerDownloadUrl" varchar(255) NOT NULL,
	"ServerDownloadUrlJava8" varchar(255) NOT NULL,
	CONSTRAINT "PK_GTNHStableVersions" PRIMARY KEY ("Id")
);

CREATE TABLE "GTNHDailyVersions"
(
	"RunNumber" bigint NOT NULL,
	"Version" varchar(32) NOT NULL,
	"Success" boolean NOT NULL,
	"CreatedAt" timestamp NOT NULL,
	"UpdatedAt" timestamp NOT NULL,
	"RunUrl" varchar(255) NOT NULL,
	"RunHtmlUrl" varchar(255) NOT NULL,
	"ClientDownloadUrl" varchar(255) NULL,
	"ClientDownloadUrlJava8" varchar(255) NULL,
	"ServerDownloadUrl" varchar(255) NULL,
	"ServerDownloadUrlJava8" varchar(255) NULL,
	CONSTRAINT "PK_GTNHDailyVersions" PRIMARY KEY ("RunNumber")
);
