-- Create WillhabenConfigs table for storing search configurations
-- Create WillhabenSeenListings table for tracking already found Willhaben offerings

CREATE TABLE "WillhabenConfigs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" varchar(255) NOT NULL,
    "Keyword" varchar(255) NOT NULL,
    "Category" integer NOT NULL,
    "Rows" integer NOT NULL,
    "PriceMin" integer NOT NULL,
    "PriceMax" integer NOT NULL,
    "FilterPaylivery" integer NOT NULL,
    "HandoverTypes" text NOT NULL,
    "AllowedStates" text NOT NULL,
    "KmMax" integer NOT NULL,
    "MustInclude" text NOT NULL,
    "MustExclude" text NOT NULL,
    "SortByDistance" boolean NOT NULL,
    "ReferenceLat" double precision NOT NULL,
    "ReferenceLon" double precision NOT NULL,
    "MaxDistanceKm" double precision NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_WillhabenConfigs" PRIMARY KEY ("Id")
);

CREATE TABLE "WillhabenSeenListings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Url" varchar(255) NOT NULL,
    "Price" double precision NOT NULL,
    CONSTRAINT "PK_WillhabenSeenListings" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_WillhabenSeenListings_Url" UNIQUE ("Url")
);
