<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>77dc80b7-05d5-41b7-b5bc-0fb3c7098ee9</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AblApi.DataAccess\AblApi.DataAccess.csproj" />
    <ProjectReference Include="..\AblApi.Repositories\AblApi.Repositories.csproj" />
    <ProjectReference Include="..\AblApi.GTNH\AblApi.GTNH.csproj" />
    <ProjectReference Include="..\AblApi.Common\AblApi.Common.csproj" />
    <ProjectReference Include="..\AblApi.Core\AblApi.Core.csproj" />
    <ProjectReference Include="..\AblApi.GTNH\AblApi.GTNH.csproj" />
  </ItemGroup>

</Project>
