name: Build images

on: 
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/define-test.yml
    secrets: inherit

  build-push:
    requires: [test]
    uses: ./.github/workflows/define-build-push.yml
    with:
      push_image: false
    secrets: inherit
